### ISSUE TITLE
Unneeded line in Q1.py

### ISSUE THREAD

**Issue by icbicket** [JingyiQQQ/A406-1#2]
The i+1 is not needed in Python for loops.

https://github.com/JingyiQQQ/A406-1/blob/e39b4f57118424806cd19ed3624f167b176f22df/Assignment2/Q1.py#L16

**Comment by JingyiQQQ** [comment]
i can only see your comments but not correct on my Github, right?

**Comment by icbicket** [comment]
Yes, you can correct the code in your repository on your local computer, then commit and push again. You can even reference the issue in your commit message :)
