### ISSUE TITLE
What is this file?

### ISSUE THREAD

**Issue by icbicket** [JingyiQQQ/A406-1#3]
What does this file do?

https://github.com/JingyiQQQ/A406-1/blob/e39b4f57118424806cd19ed3624f167b176f22df/Assignment2/Q4.py#L1

**Comment by JingyiQQQ** [comment]
it's the previous version of your question 4 file. As you mentioned earlier, it's not necessary to create a new one but just operate over your file i suppose?

**Comment by icbicket** [comment]
Oops, my mistake, I forgot what it looked like :). Yes, you can just operate over mine. If you make a mistake or delete something you didn't mean to, it's saved in the commit history.

**Comment by JingyiQQQ** [comment]
okay! Thank U so much!
